### ISSUE TITLE
[Feature] Config to have LootCrates restock 

### ISSUE THREAD

**Issue by Mattabase** [DaFuqs/LootCrates#10]
A config option or config options

1. Have the replaced vanilla chests restock
2. How often they restock

I am working on a modpack and I am tweaking dungeons to be something I want players to come back too.

So for example, an event in my pack is a Blue Moon, on a blue moon you have a luck effect applied that will rolls a bonus loot table when looting chests, so player would track locations of dungeons and make sure to go fight and loot them again on such events.

**Comment by DaFuqs** [comment]
Next version will have a simple config option for that at least. It's not highly configurable yet, but enough to get you started. :)
