### ISSUE TITLE
[Feature] Open Chests From Inventory

### ISSUE THREAD

**Issue by milkev** [DaFuqs/LootCrates#15]
**What I Want**
To be able to right click a loot crate in my hand and have it open and deposit the loot either in my inventory or on the ground where i am.

**Why**
I was hoping i could use this as a sort of loot bag mob drop in combination with eldritch mobs, as having the eldritch mobs just drop their loot directly (custom or default) clogs up the players inventory extremely quickly. 
I understand that this isnt really a loot bag mod... but theres not really any other loot-bag-like mod out there so :) sorry if this is considered outside the scope of this mod.

**Comment by DaFuqs** [comment]
Take a look at https://github.com/kyrptonaught/quickshulker. The awesome @kyrptonaught added support to open Loot Crates with it.
This might be exactly what you are thinking of. And it works for other blocks, too!

**Comment by milkev** [comment]
thats odd, i have the latest version of quick shulker and loot crates and its not working (though it does cause some other strange issues)
unfortunately, isnt quite what i was thinking of though, if it works how i imagine its supposed to. I was hoping the crates could be opened en masse (like opening a stack at once, if you really wanted to... though that would probably cause a fair bit of lag) and consume the crates as if you placed and broke them

**Comment by kyrptonaught** [comment]
Thanks for the plug! 

What issues are you experiencing with quickshulker? Feel free to open an issue on the linked GitHub above and I'll try my best to get to it when possible. 

It is technically possible with the quickshulker api to open and dump the entire stack of the held crates into your inventory. The api does provide you with the player and the stack they "quickshulker-ed". Rather than reading the contexts of the crate and opening the inventory screen showing you, they could instead all have their inventory contents dumped into your inventory. Maybe if the player is sneaking?

**Comment by DaFuqs** [comment]
For a quick test I could not find any issues with the quick shulker compatibility just using loot crates & quick shulker. But maybw @milkev can give a hint on that they mean. That said I added quickshulker to loot crates "suggests" list. If anyone even looks at that.

I am thinking about adding a new category "loot bags" additionally to chests and shulkers. That would be better understandable for players, than chests or shulkers dumping their inventory or vanishing. I am currently Improving quick shulker support by automatically unlocking crates in inventory and consuming a key, as a first step to loot bags. (then again, unlocking a bag would be silly, but by providing that option it is for the modpack creator to decide, I guess)

**Comment by DaFuqs** [comment]
https://streamable.com/bkdxrq

Kinda like you imagined, @milkev ? 😁

**Comment by milkev** [comment]
yeah! that looks awesome

**Comment by DaFuqs** [comment]
Added in 1.4.0 ✔
