### ISSUE TITLE
[Feature] Lootbag (LootCraft - Lootcontainer) Opener

### ISSUE THREAD

**Issue by Mattabase** [DaFuqs/LootCrates#17]
With the addition of lootbags, it reminds me one of the nice end game things when it comes to lootbags is having a way to open them that is not the player. So having a block that you could place lootbags (Perhaps all lootcrates) into that would then open the loot for automation purposes would rock. 

The big reason I bring this up is I intend to use this for a bunch of my projects and one of those involves lots of mob farms, I would love to have lootbags drop from mobs, without a way to auto open them all, opening bags could consume many hours of play.

Heck even if you just allowed a dispenser to open the bags into the world that would do the trick

**Comment by DaFuqs** [comment]
Using a dispenser was exactly the thing I was thinking of! I am also adding comparator & dispenser support for crates and chests to empty them via shulker unloaders.
Not sure if you would have a more techy solution, but that seemed most intuitive for vanilla users, I thought.

**Comment by Mattabase** [comment]
Dispenser and comparator support should do the job in my opinion, it matches with Vanillas emergent design standards
