### ISSUE TITLE
[BUG] Modular loot crates + battle towers and modded chests

### ISSUE THREAD

**Issue by Chuunkyz** [DaFuqs/LootCrates#19]
Hey,
chests aren't replaced with modular loot crates in draylar's battle towers
for end cities datapack chests (i don't know if this is because they are modded chests), the chests are replaced with loot crates but they are empty...
also how can i choose the chest type for each structure ?
i mean 'wooden' common loot crates in the end is not really cool

**Comment by DaFuqs** [comment]
Do draylar's battle towers and the end cities datapack chests use loot tables for their chest loot, or do they just set the contents of the chests directly?

For changing the chest type of end city (or all other) chests, you can use the config. You can find an example on how to use the config with descriptions here:
https://github.com/DaFuqs/LootCrates/blob/main/example_datapacks/default_config.json5

Add an entry like:
```{
    "loot_table": "minecraft:<<end_city_loot_table_name>>",
    "entries": [
      {
        "crate_rarity": "epic",
        "once_per_player": true,
        "replenish_time_ticks": 1
      }
}

**Comment by Chuunkyz** [comment]
i think draylar's battle towers use random chest placement instead of chests in nbt structures, maybe that's the problem
but aisde that, it uses loot tables ye.

**Comment by DaFuqs** [comment]
2.0.1 improves the way, some chest generations are handled. That may resolve your datapacks issue. It also comes with an expanded default config to use specific crate types where it makes sense (like rare crates in ocean monuments, or epic ones in the end).

What I could not resolve was the BattleTowers one. [It places the chests via a different entity after world gen.](https://github.com/Draylar/battle-towers/blob/684be2c305dab0c3ee6ec2fb2f04a0473ff193e6/src/main/java/draylar/battletowers/entity/block/ContentDeployerBlockEntity.java)
