### ISSUE TITLE
[Feature] Lootbox auto-relock

### ISSUE THREAD

**Issue by chemicalursine** [DaFuqs/LootCrates#21]
I have a server I wish to open for a small community and I love the concept of the mods, I'm planning to make keys earned by completing quests, unfortunately something is missing from the mods that I wish was there.
The ability to have the box lock itself back each time the loot is back inside. This type of system would make renewable loot boxes a thing on servers and I think it's important.

**Comment by DaFuqs** [comment]
Ping me when you have opened the server. I would love to come around some day. :)
