### ISSUE TITLE
[BUG] Cannot blacklist biomes

### ISSUE THREAD

**Issue by red2blue** [DaFuqs/LootCrates#24]
After entering any blacklisted biome in the correct format of a array, the config file resets and the blacklist goes back to the default blacklisted biome, spectrum. 

I tried leaving spectrum in there, and taking it out, all the time the lootcrates config resets with the biome going back to the default one.

Note: only blacklisted config entry resets, everything else stays the same.

Latest version, 1.17.1 fabric.

**Comment by DaFuqs** [comment]
Are we talking about biomes or dimensions here?
The only config setting there is to exclude stuff from worldgen is about dimensions.

**Comment by red2blue** [comment]
Dimensions

**Comment by DaFuqs** [comment]
this one is fixed in the version >2.1.2
