### ISSUE TITLE
[BUG] Newest update today made problem worse

### ISSUE THREAD

**Issue by red2blue** [DaFuqs/LootCrates#25]
So I turned on the server and immediately got spammed... a lot.... of this https://pastebin.com/bBGHYdDS
 
 I never received this message in console 2 updates ago.. weird.

**Comment by DaFuqs** [comment]
Can you upload your pack as a multimc instance or something similar? That would help a ton.

**Comment by red2blue** [comment]
https://pastebin.com/3EWUH4XM Here is the logs from my 2nd server. This latest update, and the last, effectively killed chest loot tables and stopped chests from generating into the world. 

My modpack can be found at https://www.curseforge.com/minecraft/modpacks/another-quality-modpack-2

**Comment by DaFuqs** [comment]
I will look into it tomorrow. In the meantime using the old version will
work fine.

red2blue ***@***.***> schrieb am So., 7. Nov. 2021, 21:43:

**Comment by DaFuqs** [comment]
The one you only had occasional issues with was 2.1.0.

I tried and tried, but could not recreate the error messages from the log you were posting. Can you send a complete startup log? The only way I can imagine the errors triggering is with Loot Crate Block Entities to register at all. If yes, there could be a stacktrace there.

I tried with:
Client: AQM2 [v2.9.5a] Hotfix (newest one on curseforge)
Server: AQM2-2.9.5a.zip (the newest one linked on the discord)
changing the version of LootCrates to 2.2.0
and then flying, teleporting and walking all around the place. Crates seemed to generate normally, NBT data fully intact and functional. Are you using a newer, dev vesion of the pack?

**Comment by red2blue** [comment]
I deleted the mod because it was giving insane lag with those messages ^. now I'm getting spammed [WARN] (class_2586) Skipping BlockEntity with id lootcrates:chest_loot_crate_block_entity


Nope, I'm using the version you downloaded. every people gave me their logs and it happened to them as well. Are you running a dedicated server or just going into single player?

Maybe try running it with 2.1.2, generating chunks, structures, etc, then upgrade to 2.2.0

**Comment by DaFuqs** [comment]
Those warning messages are the vanilla way to tell you there was stuff in a
saved chunk that it dis not recognize anymore (deleted a mod, or by
downgrading a 1.17 world to 1.16). There is nothing to worry about, since
you know what the cause of the message is. Once every chunk where loot
crates did exist before are loaded once no new messages of that type will
appear (since the obsolete data has all been removed)

I was using the client pack via multi mc and joined onto the dedicated
server, with a few restarts to make sure.
I will try your suggestion. Definitely worth a try!


red2blue ***@***.***> schrieb am Mo., 8. Nov. 2021, 20:55:

**Comment by red2blue** [comment]
gotcha. yeah I recommend running it on a server. it doesn't do it in single
player.

**Comment by DaFuqs** [comment]
I tried a world upgrade with LootCrates 1.5.0 (the last 1.x version), and 2.0.1 both on dedicated server. Both had no issues, sadly.

The last thing, that I could imagine, is the config. That definitely would be a thing happening at startup. Could you please try deleting the config files
LootCrates.json5
LootCratesWorldgenSettings.json5

and check if the issue persists?

**Comment by red2blue** [comment]
I can try it but I'm concerned about this vanilla message getting spammed.
it's been three days now and both servers are constantly getting spammed
with it in console. there isn't a time we're there aren't people playing on
the servers. it should be done by now. I guarantee the same.message is
happening for the same chests, especially at the rate it's firing these
messages in console.
