### ISSUE TITLE
[BUG] Quick Shulker Combatibility Crash Report

### ISSUE THREAD

**Issue by RubyRezal** [DaFuqs/LootCrates#27]
**Describe the bug**
Minecraft 1.18
Fabric Loader 0.12.8
Modular Loot Crates 2.4.0-1.18.0
Quick Shulker 1.3.1-1.18

**To Reproduce**
Launch Minecraft

**Expected behavior**

**Screenshots**
[crash-2021-12-01_11.01.43-server.txt](https://github.com/DaFuqs/LootCrates/files/7635471/crash-2021-12-01_11.01.43-server.txt)

**Comment by DaFuqs** [comment]
Fixed in 2.5.0 via https://github.com/DaFuqs/LootCrates/commit/3dda32f4bf6fb6470e8984a1c705e0db590991a0
