### ISSUE TITLE
Can't get loot bags working

### ISSUE THREAD

**Issue by JPearl-git** [DaFuqs/LootCrates#28]
Hello,

I've been experimenting with making a datapack using this mod, but I'm having trouble getting the loot bags to spawn with items (from a loot table). I've tried to construct the json the same way as the other crates, but every time it spawns the loot bag, its empty. This is what i'm using:
 
{
            "rolls": 1,
            "entries": [
                {
                    "type": "item",
                    "name": "lootcrates:common_loot_bag",
                    "weight": 1,
                    "functions": [
                        {
							"function": "set_nbt",
							"tag": "{BlockEntityTag: {LootTable: \"minecraft:chests/bastion_treasure\"}, display: {Name: '{\"text\":\"Common Loot Bag\"}'}}"
						}
                    ]
                }
            ]
        }

**Comment by DaFuqs** [comment]
you can find an example here:
https://github.com/DaFuqs/LootCrates/tree/1.18/example_datapacks

Otherwise feel free to join me on the Spectrum Discord and I can help you out personally. :)

**Comment by JPearl-git** [comment]
Okay, what's the link to the discord
