### ISSUE TITLE
[BUG] Mod conflict with Probably Chests (Java 1.19 Fabric 0.14.9)

### ISSUE THREAD

**Issue by ghost** [DaFuqs/LootCrates#34]
**Describe the bug**
Using both mods default configuration, the chests spawned from Probably Chests seem to have their loot table reloaded and the chest ends up being empty. The only solution I have found to allow Probably Chests to work properly is to set "ReplaceVanillaWorldgenChests" to false inside one of this mods config files: LootCrates.json, however this of course results in there being no Modular Lootcrates being spawned anywhere. I have spoken to the mod author for Probably Chests (ArcanePigeon) and he recommended me to post this issue as well as say he will look into his side of things when he has the chance because his chest shouldn't be labelled as vanilla chests anywhere.

Minecraft Java 1.19
Fabric version 0.14.9
Modular Lootcrates version 2.9.0-1.19
Probably Chests version 0.5.4-1.19.1

Probably Chests Link: https://www.curseforge.com/minecraft/mc-mods/probably-chests

**To Reproduce**
Using both mods default configuration. Open any one of the chests spawned in the overworld from Probably Chests. The inventory will appear with loot, immediately close and reopen completely empty.

**Expected behavior**
When opening any one of the chests spawned in the overworld from Probably Chests, loot should be inside the chest. (so long as the chest isn't a mimic of course.)

**Screenshots**
N/A

**Comment by DaFuqs** [comment]
I will check it out

**Comment by DaFuqs** [comment]
looks like probably chests is pretty much ded :(
