### ISSUE TITLE
[Feature] Break/delete key when unlocking a chest

### ISSUE THREAD

**Issue by URSFR** [DaFuqs/LootCrates#35]
Is it possible to add a setting or new keys that break when used to unlock one chest?

**Comment by DaFuqs** [comment]
Absolutey! It should already be possible. Take a look here: https://github.com/DaFuqs/LootCrates/wiki/Loot-Crates-(Chests,-Barrels,-Shulkers)

Changing the entry `LockMode` for a crate in the config changes if a key is getting used up, or is only needed to open.

**Comment by URSFR** [comment]
ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh i misunderstood the config, thx
