### ISSUE TITLE
How to Customize Loot Tables

### ISSUE THREAD

**Issue by f3nikkusu** [DaFuqs/LootCrates#36]
I'm a bit new to code and couldn't find a loot tables file within the config. Can you point me in the right direction?

Fabric 1.19.2

**Comment by DaFuqs** [comment]
The mod does not ship any loot tables itself, but retains the vanilla / mod loot tables everywhere.
You can create your own ones and add them via data pack. Here are some cool ressources:

Some examples of customisations: https://github.com/DaFuqs/LootCrates/tree/3.0.0%2B1.19.2/example_datapacks/3.x.x_pack_version_10
The full loot crate documentation: https://github.com/DaFuqs/LootCrates/wiki/Loot-Crates-(Chests,-Barrels,-Shulkers)
Visual loot table editor: https://misode.github.io/loot-table/
