### ISSUE TITLE
Example for inventory tag in wiki

### ISSUE THREAD

**Issue by Abisos** [DaFuqs/LootCrates#37]
I can't figure out how to use the inventory tag in a give command. It says with a list analog to shulker box. I tried it with this or parts of it, but without success: 
`{BlockEntityTag:{Items:[{Slot:16,id:netherite_sword,Count:1,tag:{Custom:{ArmorSet:1}, CustomModelData:1}}]}}
`
A short example would be really appreciated.

**Comment by DaFuqs** [comment]
Sorry to only answer you now.
Looks like the info in the wiki was outdated a bit in this point. I will go ahead and update it asap!

Here is a working example:
`/give Player329 lootcrates:blaze_chest_loot_crate{BlockEntityTag: {Items: [{Slot: 4b, id: "minecraft:iron_leggings", Count: 1b, tag: {Damage: 0}}]}} 1`
