### ISSUE TITLE
hasTransparency client kick issue

### ISSUE THREAD

**Issue by profjb58** [DaFuqs/LootCrates#4]
**Describe the bug**
When placing a lootcrate if another user loads the chunk the loot crate was placed at there is a possibility they will get kicked from the server. It seems like a server > client desync issue whereby information on `hasTransparency` is sent to the player placing the loot crate but not additional players on the server. Seems to happen here: https://github.com/DaFuqs/LootCrates/blob/master/src/main/java/de/dafuqs/lootcrates/LootCrateAtlas.java#L144https://github.com/DaFuqs/LootCrates/blob/master/src/main/java/de/dafuqs/lootcrates/LootCrateAtlas.java#L144

This has happened twice on 2 different types of servers and is not due to Sodium + Indium (I asked what the players where running) which is a common theme for rendering issues. Also the latest version `1.0.0`

**Client crash report**: https://gist.github.com/profjb58/7ac4c3af4741bf1189dd78766fdc6dff

**To Reproduce**
1. Place a lootcrate on a dedicated server
2. Have another player who is already logged in move into the region you placed the lootcrate
3. That player when entering the chunk region can on occasion be kicked from the server (a client crash happens)

**Expected behavior**
The other player should not crash

**Desktop (please complete the following information):**
Irrelevant I think, using OpenJDK 8 however. Not sure what the other player was using.

**Smartphone (please complete the following information):**
?

**Comment by profjb58** [comment]
p.s. if you want to reproduce just let me know and i'm happy trying it again

**Comment by DaFuqs** [comment]
Oh, that's good to know! I'll check that out right tomorrow

**Comment by DaFuqs** [comment]
I guess that happens will all types of chests, not just the ghost crates?

**Comment by profjb58** [comment]
I think so yeah :)

**Comment by DaFuqs** [comment]
VERY weird. I could not reproduce that in my local server and client scenario at all, but it may very well be a very rare scenario where the crate renderer is just a tick more early than he should or the mod not starting up correctly.
I've added a failsave for that for problematic frames and updated all dependencies. See releases.

**Comment by profjb58** [comment]
Did you have a chance to test with other players? Doesn't seem to affect the player that places the crate

**Comment by DaFuqs** [comment]
I restarted the client multiple times after placing, joined the world, walked to the crates and restarted again (different player uuid). So... kind of.

**Comment by profjb58** [comment]
If you want to test on a dedicated server btw im happy helping :).
I think its not gonna happen on single-player since it seems like a desync error. Maybe  its an issue whereby 2 or more players are loading the same chunks so disconnecting from a server and re logging will re load the chunk which will make sure data is sent from the server to the client so there is no desync issue

**Comment by DaFuqs** [comment]
Sadly I've got lots of stuff to do atm, but I'd love to swing around some day and test it out in detail. I'll see around in the discord :)
