### ISSUE TITLE
Rendering transparency while back from another dimmension

### ISSUE THREAD

**Issue by panbanann** [DaFuqs/LootCrates#5]
https://pastebin.com/7zL6kVS2
I had a common shulker crate next to the portal from another mod. When I teleported back to the overworld, the game crashed with this crash report.

**Comment by DaFuqs** [comment]
What mod was it? I could not reproduce it with vanillas portals / the tp command.
Or was it multiplayer?

**Comment by DaFuqs** [comment]
Fixed via https://github.com/DaFuqs/LootCrates/commit/c195349b53a6f676f0e0737b372cba40414a87be
